<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-JR7VQ45M" failures="2" tests="4" name="Login Tests" time="16.623" errors="0" timestamp="2025-07-05T13:52:41 IST">
  <testcase classname="tests.LoginTests" name="loginTest" time="14.195"/>
  <testcase classname="tests.LoginTests" name="loginTestDataProvider" time="0.569"/>
  <testcase classname="tests.LoginTests" name="loginTestDataProvider" time="0.169">
    <failure type="java.lang.AssertionError" message="expected [Logged In Successfully | Practice Test Automation] but found [Test Login | Practice Test Automation]">
      <![CDATA[java.lang.AssertionError: expected [Logged In Successfully | Practice Test Automation] but found [Test Login | Practice Test Automation]
at tests.LoginTests.loginTestDataProvider(LoginTests.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- loginTestDataProvider -->
  <testcase classname="tests.LoginTests" name="loginTestDataProvider" time="0.151">
    <failure type="java.lang.AssertionError" message="expected [Logged In Successfully | Practice Test Automation] but found [Test Login | Practice Test Automation]">
      <![CDATA[java.lang.AssertionError: expected [Logged In Successfully | Practice Test Automation] but found [Test Login | Practice Test Automation]
at tests.LoginTests.loginTestDataProvider(LoginTests.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- loginTestDataProvider -->
</testsuite> <!-- Login Tests -->
